version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: neuralizard
      POSTGRES_PASSWORD: neuralizard
      POSTGRES_DB: neuralizard
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neuralizard"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"

  api:
    build: .
    env_file:
      - .env
    environment:
      DB_URL: postgresql+psycopg://neuralizard:neuralizard@db:5432/neuralizard
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      XAI_API_KEY: ${XAI_API_KEY}
    volumes:
      - ./src:/app/src
    command: uvicorn neuralizard.api.server:app --host 0.0.0.0 --port 8001 --reload
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      VITE_API_BASE: http://localhost:8001
    depends_on:
      - api
    ports:
      - "5173:5173"

  pgweb:
    image: sosedoff/pgweb
    environment:
      PGWEB_DATABASE_URL: postgres://neuralizard:neuralizard@db:5432/neuralizard?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  pgdata:
  frontend_node_modules: