apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: neuralizard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          # Replace with your locally built image tag, e.g., neuralizard-api:local
          image: neuralizard-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: DB_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: POSTGRES_DB
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: OPENAI_API_KEY
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: ANTHROPIC_API_KEY
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: GOOGLE_API_KEY
            - name: MISTRAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: MISTRAL_API_KEY
            - name: COHERE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: COHERE_API_KEY
            - name: XAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: XAI_API_KEY
          args:
            - uvicorn
            - neuralizard.api.server:app
            - --host
            - 0.0.0.0
            - --port
            - "8001"
          readinessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: neuralizard
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP
