apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  namespace: neuralizard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
        - name: pgweb
          image: sosedoff/pgweb:latest
          ports:
            - containerPort: 8081
          env:
            - name: PGWEB_DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: neuralizard-secrets
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb
  namespace: neuralizard
spec:
  selector:
    app: pgweb
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
