apiVersion: v1
kind: Secret
metadata:
  name: neuralizard-secrets
  namespace: neuralizard
type: Opaque
stringData:
  # Database credentials (used by Postgres and API)
  POSTGRES_USER: neuralizard
  POSTGRES_PASSWORD: neuralizard
  POSTGRES_DB: neuralizard

  # Provider API keys (optional; leave empty if unused)
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  GOOGLE_API_KEY: ""
  MISTRAL_API_KEY: ""
  COHERE_API_KEY: ""
  XAI_API_KEY: ""
